name : "Terraform-plan-Infra-plan"

on:
  push:
    branches: sandbox

jobs:
  terraform:
    name: "terraform"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}
      AWS_REGION: "us-east-1"

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform plan
        id: plan
        if: github.event_name == 'push'
        run: terraform plan -no-color